name: glados-checkin

on:

  schedule:
  - cron: 21 7 * * *

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run checkin
        run: |
          python3 ./main.py --cookie_string "${{ secrets.COOKIE }}"
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SCKEY }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
      - uses: gautamkrishnar/keepalive-workflow@master
